name: olivers-raspberry-pi
services:
  n8n:
    stdin_open: true
    tty: true
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n
    environment:
      - N8N_SECURE_COOKIE=false
volumes:
  n8n_data:
    external: true
    name: n8n_data
